### ISSUE TITLE
STT DEMO KWS -- Profanity is erroneously not obscured by a series of asterisks in the output, when profanity_filter is set to true to block profanity			

### ISSUE THREAD

**Issue by Atreilly** [leonrch/speech-to-text-nodejs#12]
Leonid,					
	I tested this using Chrome and Firefox and got the same results. Attached are screen shots from Firefox.					
						
	Upon entry to the STT Demo (https://speech-to-text-demo-lr.mybluemix.net/), selecting the US English broadband model, the user records audio using some profanities.					
1	The user selects the US English Broadband model					
2	The user enter a profanity in the keyword spotting box.					
3	The user records his/her voice with profanities, by pressing the "Record Audio" button.					
4	**His/her recording is transcribed in the text box. All words, except profanity words are in the text box. There are erroneously no asterisks and no other indication in the output that a profanity was recorded. See "By default, the parameter is set to true, meaning that all profanity is obscured by a series of asterisks in the output.", in section A in attached spreadsheet.		
5	The profanity is spotted in the "Keywords Spotted" section					
6	**The profanity replaced with asterisks is displayed in the confusion networks box. -- Is this correct? Or should the actually profanity be listed here? See "The sole exception is keyword spotting, for which the service returns all words as specified by the user, regardless of whether profanity_filter is true.", in see section B in attached spreadsheet.			
7	The profanity is listed in JSON.	

See attached screen shots for details.

Alexandra

**Comment by Atreilly** [comment]
[STT DEMO KWS -- Profanity is erroneously missing a series of asterisks in the output when profanity_filter is set to true to block profanity.xlsx](https://github.com/leonrch/speech-to-text-nodejs/files/141647/STT.DEMO.KWS.--.Profanity.is.erroneously.missing.a.series.of.asterisks.in.the.output.when.profanity_filter.is.set.to.true.to.block.profanity.xlsx)

**Comment by leonrch** [comment]
Please try it out.

**Comment by Atreilly** [comment]
Leonid,

This works. Thank you.

I will close this issue now.

Alexandra
[STT DEMO KWS -- Profanity is erroneously missing a series of asterisks in the output when profanity_filter is set to true to block profanity.xlsx](https://github.com/leonrch/speech-to-text-nodejs/files/145604/STT.DEMO.KWS.--.Profanity.is.erroneously.missing.a.series.of.asterisks.in.the.output.when.profanity_filter.is.set.to.true.to.block.profanity.xlsx)
