### ISSUE TITLE
STT DEMO KWS -- Keyword spotting box erroneously empty for all selected narrowband models for sample audios

### ISSUE THREAD

**Issue by Atreilly** [leonrch/speech-to-text-nodejs#2]
Hi Leonid,

On the STT demo page (via this link -->https://speech-to-text-demo-lr.mybluemix.net/), to "Transcribe Audio" from speech to text, the user must select a model.
When selecting any narrowband model listed below, no keywords are populated in the keyword spotting box, to use with either of the audio samples (“Play Sample 1”, “Play Sample 2”), as they are for all broadband models.

STT DEMO KWS DEFECT -- Keyword spotting box erroneously empty for all selected narrowband models for sample audios.xlsx

US English narrowband model (8KHz)                              
UK English narrowband model (8KHz)                              
Spanish narrowband model(8KHz)                              
Japanese narrowband model (8KHz)                                
Brazilian Portuguese narrowband model (8KHz)                                
Mandarin narrowband model (8KHz)                                

See attached spreadsheet for screen shots and details.

Please let me know if you have any questions or comments.

Alexandra
[STT DEMO KWS DEFECT -- Keyword spotting box erroneously empty for all narrowband model in samples.xlsx](https://github.com/leonrch/speech-to-text-nodejs/files/132779/STT.DEMO.KWS.DEFECT.--.Keyword.spotting.box.erroneously.empty.for.all.narrowband.model.in.samples.xlsx)

**Comment by leonrch** [comment]
I am going to add the default keywords. Will keep you posted ...

**Comment by leonrch** [comment]
Fixed. Please try it out.

**Comment by Atreilly** [comment]
Leonid, 
Thank you for your fixes. 

I successfully tested the following narrowband models and see default keywords in Keywords Spotting box. I will close this issue now.
US English narrowband model (8KHz)
UK English narrowband model (8KHz)
Spanish narrowband model(8KHz)
Japanese narrowband model (8KHz)
Brazilian Portuguese narrowband model (8KHz)
Mandarin narrowband model (8KHz) 

Alexandra
