### ISSUE TITLE
STT DEMO KWS -- FLAC audio file is not supported in Firefox, even though FLAC mentioned in "Transcribe Audio" section

### ISSUE THREAD

**Issue by Atreilly** [leonrch/speech-to-text-nodejs#3]
Leonid,

On the STT demo page (via this link -->https://speech-to-text-demo-lr.mybluemix.net/), to "Transcribe Audio" from speech to text, the user selects a FLAC file, however receive message that no audio will accompany the transcription.

I uploaded a flac file (STT/english/broad/001.flac – I can't attach it below, but I will send it to you if needed), as per instructions in the “Transcribe Audio” section, however, received a note that “browsers do not support playing FLAC audio, so no audio will accompany the transcription”.
a) Why doesn't firefox support playing FLAC audio if it is mentioned in the “Transcribe Audio” section?
b) Why does message state the word “browsers” in plural? Right now we're only referring to one firefox brower. Shouldn't it say, “Notice: This browser does not support playing FLAC audio, so no audio will accompany the transcription.” and end with a period?

See attached spreadsheet for screen shots and details.

Please let me know if you have any questions or comments.

Alexandra

[STT DEMO KWS DEFECT -- FLAC audio file is not supported in Firefox, even though Transcribe Audio section mentions it.xlsx](https://github.com/leonrch/speech-to-text-nodejs/files/132783/STT.DEMO.KWS.DEFECT.--.FLAC.audio.file.is.not.supported.in.Firefox.even.though.Transcribe.Audio.section.mentions.it.xlsx)

**Comment by arla916** [comment]
Regarding question a), we can transcribe FLAC files but the playback may not work in all browsers.  But the main transcription service works so I think it's fine the way it is.  The playback (which is not mentioned anywhere) is just an extra bonus.

**Comment by leonrch** [comment]
Regarding a). -- please take a look at 
https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats. 
The table shows what audio formats are supported by various browsers. FLAC is the "unlucky" one.
b). - fixed

**Comment by Atreilly** [comment]
Leonid, 

Thank you for your fix.

Here's the summary.
a) OK, was not a problem.
b) Fixed, tested, and OK now.

I will close this issue now.

Alexandra
