### ISSUE TITLE
STT DEMO KWS -- Selected broadband model, but uploaded narrowband model and erroneously did NOT receive “Upsampling not allowed because recognition accuracy will suffer. Sampling rate of at least 16000 required.”

### ISSUE THREAD

**Issue by Atreilly** [leonrch/speech-to-text-nodejs#5]
Leonid,

On the STT demo page (via this link -->https://speech-to-text-demo-lr.mybluemix.net/), to "Transcribe Audio" from speech to text, the user selects a broad model to upload, but actually uploads a narrowband file, however no error message was displayed.

I uploaded a 002.opus US English narrowband audio file--I can't attached it here, but let me know if you need it), even though I selected “US English broad model (16KHz)” and did not receive the following expected error message:

“Upsampling not allowed because recognition accuracy will suffer. Sampling rate of at least 16000 required.”

See attached spreadsheet for screen shots and details.

STT DEMO KWS DEFECT-- Selected broadband model but uploaded narrowband model and erroneously did NOT receive --Sampling rate of at least 16000 required.xlsx

Please let me know if you have any questions or comments.

Alexandra
[STT DEMO KWS DEFECT-- Selected broadband model but uploaded narrowband model and erroneously did NOT receive --Sampling rate of at least 16000 required.xlsx](https://github.com/leonrch/speech-to-text-nodejs/files/132791/STT.DEMO.KWS.DEFECT--.Selected.broadband.model.but.uploaded.narrowband.model.and.erroneously.did.NOT.receive.--Sampling.rate.of.at.least.16000.required.xlsx)

**Comment by arla916** [comment]
Alexandra, are you sure that this .opus file is 8KHz?  How did you get it or generate it?  Could it be that it was originally 8khz (it sounds like 8khz) but then in your conversion step it was actually upsampled and stored as 16khz or higher?  This would explain why no error message is being generated.

**Comment by arla916** [comment]
Alexandra, I verified with Charles that the original file was a 44KHz audio file, not 8KHz.  So that's why this works and you don't get the error message.  Please try again with the 8KHz version that Charles sent.

**Comment by Atreilly** [comment]
Tony, 

I tried Charles new file (002-8k.ogg), which was indeed a 8KHz ogg audio file, and successfully received the following expected message: "Upsampling not allowed because recognition accuracy will suffer. Sampling rate of at least 16000 required.".

I will close this issue.

Alexandra
