### ISSUE TITLE
STT DEMO KWS -- Selected non-English model, but uploaded English model and erroneously did NOT receive any type of message about the discrepancy between different language models

### ISSUE THREAD

**Issue by Atreilly** [leonrch/speech-to-text-nodejs#6]
Leonid,

On the STT demo page (via this link -->https://speech-to-text-demo-lr.mybluemix.net/), to "Transcribe Audio" from speech to text, when the user selects a non-English model, but uploads English model, no error message is displayed.

I uploaded a 002.wav US English narrowband audio file (note: I can't attach it here; please let me know if you need it), but selected “Japanese narrowband model (8KHz)” and did not receive any type of message about the discrepancy between different language models.

See attached spreadsheet for screen shots and details.

STT DEMO KWS -- Selected non-English model, but uploaded English model and erroneously did NOT receive any type of message about the discrepancy between different language models.xlsx

Please let me know if you have any questions or comments.

Alexandra
[STT DEMO KWS -- Selected non-English model, but uploaded English model and erroneously did NOT receive any type of message about the discrepancy between different language models.xlsx](https://github.com/leonrch/speech-to-text-nodejs/files/132800/STT.DEMO.KWS.--.Selected.non-English.model.but.uploaded.English.model.and.erroneously.did.NOT.receive.any.type.of.message.about.the.discrepancy.between.different.language.models.xlsx)

**Comment by arla916** [comment]
There is no way for the speech recognition engine to know what the language of the audio is.  We don't have a language detection module and there is no metadata in the WAV file that can tell us what the language of the audio is.  I believe this issue should be closed as "working-as-designed".

**Comment by Atreilly** [comment]
I will closed this issue as per arla916.

Alexandra
