### ISSUE TITLE
STT DEMO KWS -- Inconsistencies with punctuation: Some messages end in a period and some do not

### ISSUE THREAD

**Issue by Atreilly** [leonrch/speech-to-text-nodejs#7]
Leonid,

On the STT demo page (via this link -->https://speech-to-text-demo-lr.mybluemix.net/), depending on the scenario, some times I get a message.

Why do some messages end with a period and some do not? See list below:

Upsampling not allowed because recognition accuracy will suffer. Sampling rate of at least 16000 required. (Sentence ends with a period.)

Only WAV or FLAC or Opus files can be transcribed, please try another file format (Sentence does not end with a period.)

Notice: browers do not support playing FLAC audio, so no audio will accompany the transcription (Sentence does not end with a period.)

Please let me know if you have any questions or comments.

Alexandra

**Comment by leonrch** [comment]
Fixed. Please try it out.

**Comment by Atreilly** [comment]
Thank you for the fix; this test is now successful.

These new messages were now displayed:
Upsampling not allowed because recognition accuracy will suffer. Sampling rate of at least 16000 required. (Sentence remained the same.)

Only WAV or FLAC or Opus files can be transcribed, please try another file format. (Added period to end of sentence.)

Notice: This browser does not support playing FLAC audio, so no audio will accompany the transcription. (Added period to end of sentence and corrected grammar.)

Alexandra
