### ISSUE TITLE
STT DEMO KWS -- After selecting any type of model (broadband or narrowband), playing audio sample 2 and then sample 1, and vice versa,  the default keywords erroneously remain the same.

### ISSUE THREAD

**Issue by Atreilly** [leonrch/speech-to-text-nodejs#9]
Leonid, 

	After selecting any type of model (broadband or narrowband), playing audio sample 2 and then sample 1, and vice versa,  the default keywords erroneously remain the same.

Play Sample 2 -- 
	In a severe gale like this ....
Keywords Spotted --
	round, whirling velocity, unwanted emotion

Play Sample 1 -- 
        My family absolute is fascinated by the work ....
Keywords Spotted --
        round, whirling velocity, unwanted emotion

See attached spreadsheet for details and screen shots.

Alexandra

[STT DEMO KWS DEFECT -- After selecting any type of model to play audio sample 2 and then sample 1 the default keywords erroneously remain the same.xlsx](https://github.com/leonrch/speech-to-text-nodejs/files/133409/STT.DEMO.KWS.DEFECT.--.After.selecting.any.type.of.model.to.play.audio.sample.2.and.then.sample.1.the.default.keywords.erroneously.remain.the.same.xlsx)

**Comment by Atreilly** [comment]
Leonid, 

I am still testing this issue. 

Meanwhile, I see that you appended sample 2's default keywords to sample 1'2 default keywords, and now this combination is both, sample 1's and sample 2's default keywords.
Do you think you can alternate the defaults keyword in the keyword spotting box 
sample 1 word, sample 2 word, sample 1 word, sample 2 word, etc. 
instead of all sample 1 words followed by all sample 2 words? or put them in alphabetical order? or sort them is some way?

The reason is because sample 2's default words are at the end of the keyword spotting text box and most of them are hidden.

Thank you, 
Alexandra

**Comment by leonrch** [comment]
The merged set of keywords is now sorted alphabetically. Please try it out.

**Comment by Atreilly** [comment]
Leonid,

Thank you for fixing this. This works now!
I have updated the spreadsheet (and reattached it) to include a screen shot after the fix.
I will close this issue now.

Alexandra
[STT DEMO KWS DEFECT -- After selecting any type of model to play audio sample 2 and then sample 1 the default keywords erroneously remain the same.xlsx](https://github.com/leonrch/speech-to-text-nodejs/files/141477/STT.DEMO.KWS.DEFECT.--.After.selecting.any.type.of.model.to.play.audio.sample.2.and.then.sample.1.the.default.keywords.erroneously.remain.the.same.xlsx)
